### ISSUE TITLE
pb-egret generate 失败了

### ISSUE THREAD

**Issue by Android-IT** [WanderWang/protobuf-egret#13]
{ [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "pbjs --no-convert -t static --keep-case -p protobuf\protofile GoodsInfo.proto Person.proto -o C:\Users\LUO\AppData\Local\Temp\pbegret\temp.js"
module.js:327
    throw err;
    ^

Error: Cannot find module 'fs.realpath'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\LUO\AppData\Roaming\npm\node_modules\protobufjs\cli\node_modules\glob\glob.js:44:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "pbjs --no-convert -t static --keep-case -p protobuf\\protofile GoodsInfo.proto Person.proto -o C:\\Users\\LUO\\AppData\\Local\\Temp\\pbegret\\temp.js"' }      @WanderWang @WanderWang

**Comment by yangcyer** [comment]
怎么解决的 ？？有方案了吗 ？
