### ISSUE TITLE
pb-egret generate 失败

### ISSUE THREAD

**Issue by vanex7** [WanderWang/protobuf-egret#7]
wanminhua@PC040 MINGW64 /d/TestProjects/Laya
$ pb-egret generate
.
protobuf
{ Error: Command failed: pbjs -t static -p protobuf\protofile activity.proto -o                                                                                                                                                                                                C:\Users\kod\AppData\Local\Temp\pbegret\temp.js
'pbjs' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'pbjs -t static -p protobuf\\protofi

**Comment by gkjolin** [comment]
你解决这个问题了吗？

**Comment by Android-IT** [comment]
同问这个问题。有没有人出来说一下怎么解决的
